// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ProlabBuf.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace ProlabServer {

  /// <summary>Holder for reflection information generated from ProlabBuf.proto</summary>
  public static partial class ProlabBufReflection {

    #region Descriptor
    /// <summary>File descriptor for ProlabBuf.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ProlabBufReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg9Qcm9sYWJCdWYucHJvdG8SCHR1dG9yaWFsIn4KClBsYXllckRhdGESCgoC",
            "aWQYASABKAUSKQoFc3RhdGUYAiABKA4yGi50dXRvcmlhbC5QbGF5ZXJEYXRh",
            "LlN0YXRlEgwKBHBvc1gYAyABKAISDAoEcG9zWRgEIAEoAiIdCgVTdGF0ZRII",
            "CgRNRU5VEAASCgoGQUNUSVZFEAEiSQoIR2FtZURhdGESKQoLcGxheWVyRGF0",
            "YXMYASADKAsyFC50dXRvcmlhbC5QbGF5ZXJEYXRhEhIKCmZyYW1lQ291bnQY",
            "AiABKAUiKwoLQ2xpZW50SW5wdXQSDQoFbW92ZVgYASABKAISDQoFbW92ZVkY",
            "AiABKAJCOAoUY29tLmV4YW1wbGUudHV0b3JpYWxCEUFkZHJlc3NCb29rUHJv",
            "dG9zqgIMUHJvbGFiU2VydmVyYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::ProlabServer.PlayerData), global::ProlabServer.PlayerData.Parser, new[]{ "Id", "State", "PosX", "PosY" }, null, new[]{ typeof(global::ProlabServer.PlayerData.Types.State) }, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::ProlabServer.GameData), global::ProlabServer.GameData.Parser, new[]{ "PlayerDatas", "FrameCount" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::ProlabServer.ClientInput), global::ProlabServer.ClientInput.Parser, new[]{ "MoveX", "MoveY" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  /// <summary>
  /// [START messages]
  /// </summary>
  public sealed partial class PlayerData : pb::IMessage<PlayerData> {
    private static readonly pb::MessageParser<PlayerData> _parser = new pb::MessageParser<PlayerData>(() => new PlayerData());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<PlayerData> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::ProlabServer.ProlabBufReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PlayerData() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PlayerData(PlayerData other) : this() {
      id_ = other.id_;
      state_ = other.state_;
      posX_ = other.posX_;
      posY_ = other.posY_;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PlayerData Clone() {
      return new PlayerData(this);
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 1;
    private int id_;
    /// <summary>
    /// Unique ID number for this person.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Id {
      get { return id_; }
      set {
        id_ = value;
      }
    }

    /// <summary>Field number for the "state" field.</summary>
    public const int StateFieldNumber = 2;
    private global::ProlabServer.PlayerData.Types.State state_ = 0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::ProlabServer.PlayerData.Types.State State {
      get { return state_; }
      set {
        state_ = value;
      }
    }

    /// <summary>Field number for the "posX" field.</summary>
    public const int PosXFieldNumber = 3;
    private float posX_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public float PosX {
      get { return posX_; }
      set {
        posX_ = value;
      }
    }

    /// <summary>Field number for the "posY" field.</summary>
    public const int PosYFieldNumber = 4;
    private float posY_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public float PosY {
      get { return posY_; }
      set {
        posY_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as PlayerData);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(PlayerData other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Id != other.Id) return false;
      if (State != other.State) return false;
      if (PosX != other.PosX) return false;
      if (PosY != other.PosY) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Id != 0) hash ^= Id.GetHashCode();
      if (State != 0) hash ^= State.GetHashCode();
      if (PosX != 0F) hash ^= PosX.GetHashCode();
      if (PosY != 0F) hash ^= PosY.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Id != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Id);
      }
      if (State != 0) {
        output.WriteRawTag(16);
        output.WriteEnum((int) State);
      }
      if (PosX != 0F) {
        output.WriteRawTag(29);
        output.WriteFloat(PosX);
      }
      if (PosY != 0F) {
        output.WriteRawTag(37);
        output.WriteFloat(PosY);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Id != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Id);
      }
      if (State != 0) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) State);
      }
      if (PosX != 0F) {
        size += 1 + 4;
      }
      if (PosY != 0F) {
        size += 1 + 4;
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(PlayerData other) {
      if (other == null) {
        return;
      }
      if (other.Id != 0) {
        Id = other.Id;
      }
      if (other.State != 0) {
        State = other.State;
      }
      if (other.PosX != 0F) {
        PosX = other.PosX;
      }
      if (other.PosY != 0F) {
        PosY = other.PosY;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            Id = input.ReadInt32();
            break;
          }
          case 16: {
            state_ = (global::ProlabServer.PlayerData.Types.State) input.ReadEnum();
            break;
          }
          case 29: {
            PosX = input.ReadFloat();
            break;
          }
          case 37: {
            PosY = input.ReadFloat();
            break;
          }
        }
      }
    }

    #region Nested types
    /// <summary>Container for nested types declared in the PlayerData message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static partial class Types {
      public enum State {
        [pbr::OriginalName("MENU")] Menu = 0,
        [pbr::OriginalName("ACTIVE")] Active = 1,
      }

    }
    #endregion

  }

  /// <summary>
  /// Our address book file is just one of these.
  /// </summary>
  public sealed partial class GameData : pb::IMessage<GameData> {
    private static readonly pb::MessageParser<GameData> _parser = new pb::MessageParser<GameData>(() => new GameData());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<GameData> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::ProlabServer.ProlabBufReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GameData() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GameData(GameData other) : this() {
      playerDatas_ = other.playerDatas_.Clone();
      frameCount_ = other.frameCount_;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GameData Clone() {
      return new GameData(this);
    }

    /// <summary>Field number for the "playerDatas" field.</summary>
    public const int PlayerDatasFieldNumber = 1;
    private static readonly pb::FieldCodec<global::ProlabServer.PlayerData> _repeated_playerDatas_codec
        = pb::FieldCodec.ForMessage(10, global::ProlabServer.PlayerData.Parser);
    private readonly pbc::RepeatedField<global::ProlabServer.PlayerData> playerDatas_ = new pbc::RepeatedField<global::ProlabServer.PlayerData>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::ProlabServer.PlayerData> PlayerDatas {
      get { return playerDatas_; }
    }

    /// <summary>Field number for the "frameCount" field.</summary>
    public const int FrameCountFieldNumber = 2;
    private int frameCount_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int FrameCount {
      get { return frameCount_; }
      set {
        frameCount_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as GameData);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(GameData other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!playerDatas_.Equals(other.playerDatas_)) return false;
      if (FrameCount != other.FrameCount) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= playerDatas_.GetHashCode();
      if (FrameCount != 0) hash ^= FrameCount.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      playerDatas_.WriteTo(output, _repeated_playerDatas_codec);
      if (FrameCount != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(FrameCount);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      size += playerDatas_.CalculateSize(_repeated_playerDatas_codec);
      if (FrameCount != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(FrameCount);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(GameData other) {
      if (other == null) {
        return;
      }
      playerDatas_.Add(other.playerDatas_);
      if (other.FrameCount != 0) {
        FrameCount = other.FrameCount;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            playerDatas_.AddEntriesFrom(input, _repeated_playerDatas_codec);
            break;
          }
          case 16: {
            FrameCount = input.ReadInt32();
            break;
          }
        }
      }
    }

  }

  public sealed partial class ClientInput : pb::IMessage<ClientInput> {
    private static readonly pb::MessageParser<ClientInput> _parser = new pb::MessageParser<ClientInput>(() => new ClientInput());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<ClientInput> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::ProlabServer.ProlabBufReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ClientInput() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ClientInput(ClientInput other) : this() {
      moveX_ = other.moveX_;
      moveY_ = other.moveY_;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ClientInput Clone() {
      return new ClientInput(this);
    }

    /// <summary>Field number for the "moveX" field.</summary>
    public const int MoveXFieldNumber = 1;
    private float moveX_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public float MoveX {
      get { return moveX_; }
      set {
        moveX_ = value;
      }
    }

    /// <summary>Field number for the "moveY" field.</summary>
    public const int MoveYFieldNumber = 2;
    private float moveY_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public float MoveY {
      get { return moveY_; }
      set {
        moveY_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as ClientInput);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(ClientInput other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (MoveX != other.MoveX) return false;
      if (MoveY != other.MoveY) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (MoveX != 0F) hash ^= MoveX.GetHashCode();
      if (MoveY != 0F) hash ^= MoveY.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (MoveX != 0F) {
        output.WriteRawTag(13);
        output.WriteFloat(MoveX);
      }
      if (MoveY != 0F) {
        output.WriteRawTag(21);
        output.WriteFloat(MoveY);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (MoveX != 0F) {
        size += 1 + 4;
      }
      if (MoveY != 0F) {
        size += 1 + 4;
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(ClientInput other) {
      if (other == null) {
        return;
      }
      if (other.MoveX != 0F) {
        MoveX = other.MoveX;
      }
      if (other.MoveY != 0F) {
        MoveY = other.MoveY;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 13: {
            MoveX = input.ReadFloat();
            break;
          }
          case 21: {
            MoveY = input.ReadFloat();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
