/**
 * @fileoverview
 * @enhanceable
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

goog.exportSymbol('proto.tutorial.ClientInput', null, global);
goog.exportSymbol('proto.tutorial.GameData', null, global);
goog.exportSymbol('proto.tutorial.PlayerData', null, global);
goog.exportSymbol('proto.tutorial.PlayerData.State', null, global);

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.tutorial.PlayerData = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.tutorial.PlayerData, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.tutorial.PlayerData.displayName = 'proto.tutorial.PlayerData';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.tutorial.PlayerData.prototype.toObject = function(opt_includeInstance) {
  return proto.tutorial.PlayerData.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.tutorial.PlayerData} msg The msg instance to transform.
 * @return {!Object}
 */
proto.tutorial.PlayerData.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: jspb.Message.getFieldWithDefault(msg, 1, 0),
    state: jspb.Message.getFieldWithDefault(msg, 2, 0),
    posx: +jspb.Message.getFieldWithDefault(msg, 3, 0.0),
    posy: +jspb.Message.getFieldWithDefault(msg, 4, 0.0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.tutorial.PlayerData}
 */
proto.tutorial.PlayerData.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.tutorial.PlayerData;
  return proto.tutorial.PlayerData.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.tutorial.PlayerData} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.tutorial.PlayerData}
 */
proto.tutorial.PlayerData.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setId(value);
      break;
    case 2:
      var value = /** @type {!proto.tutorial.PlayerData.State} */ (reader.readEnum());
      msg.setState(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readFloat());
      msg.setPosx(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readFloat());
      msg.setPosy(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.tutorial.PlayerData.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.tutorial.PlayerData.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.tutorial.PlayerData} message
 * @param {!jspb.BinaryWriter} writer
 */
proto.tutorial.PlayerData.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f !== 0) {
    writer.writeInt32(
      1,
      f
    );
  }
  f = message.getState();
  if (f !== 0.0) {
    writer.writeEnum(
      2,
      f
    );
  }
  f = message.getPosx();
  if (f !== 0.0) {
    writer.writeFloat(
      3,
      f
    );
  }
  f = message.getPosy();
  if (f !== 0.0) {
    writer.writeFloat(
      4,
      f
    );
  }
};


/**
 * @enum {number}
 */
proto.tutorial.PlayerData.State = {
  MENU: 0,
  ACTIVE: 1
};

/**
 * optional int32 id = 1;
 * @return {number}
 */
proto.tutorial.PlayerData.prototype.getId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/** @param {number} value */
proto.tutorial.PlayerData.prototype.setId = function(value) {
  jspb.Message.setField(this, 1, value);
};


/**
 * optional State state = 2;
 * @return {!proto.tutorial.PlayerData.State}
 */
proto.tutorial.PlayerData.prototype.getState = function() {
  return /** @type {!proto.tutorial.PlayerData.State} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/** @param {!proto.tutorial.PlayerData.State} value */
proto.tutorial.PlayerData.prototype.setState = function(value) {
  jspb.Message.setField(this, 2, value);
};


/**
 * optional float posX = 3;
 * @return {number}
 */
proto.tutorial.PlayerData.prototype.getPosx = function() {
  return /** @type {number} */ (+jspb.Message.getFieldWithDefault(this, 3, 0.0));
};


/** @param {number} value */
proto.tutorial.PlayerData.prototype.setPosx = function(value) {
  jspb.Message.setField(this, 3, value);
};


/**
 * optional float posY = 4;
 * @return {number}
 */
proto.tutorial.PlayerData.prototype.getPosy = function() {
  return /** @type {number} */ (+jspb.Message.getFieldWithDefault(this, 4, 0.0));
};


/** @param {number} value */
proto.tutorial.PlayerData.prototype.setPosy = function(value) {
  jspb.Message.setField(this, 4, value);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.tutorial.GameData = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.tutorial.GameData.repeatedFields_, null);
};
goog.inherits(proto.tutorial.GameData, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.tutorial.GameData.displayName = 'proto.tutorial.GameData';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.tutorial.GameData.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.tutorial.GameData.prototype.toObject = function(opt_includeInstance) {
  return proto.tutorial.GameData.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.tutorial.GameData} msg The msg instance to transform.
 * @return {!Object}
 */
proto.tutorial.GameData.toObject = function(includeInstance, msg) {
  var f, obj = {
    playerdatasList: jspb.Message.toObjectList(msg.getPlayerdatasList(),
    proto.tutorial.PlayerData.toObject, includeInstance),
    framecount: jspb.Message.getFieldWithDefault(msg, 2, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.tutorial.GameData}
 */
proto.tutorial.GameData.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.tutorial.GameData;
  return proto.tutorial.GameData.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.tutorial.GameData} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.tutorial.GameData}
 */
proto.tutorial.GameData.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.tutorial.PlayerData;
      reader.readMessage(value,proto.tutorial.PlayerData.deserializeBinaryFromReader);
      msg.addPlayerdatas(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setFramecount(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.tutorial.GameData.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.tutorial.GameData.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.tutorial.GameData} message
 * @param {!jspb.BinaryWriter} writer
 */
proto.tutorial.GameData.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getPlayerdatasList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      proto.tutorial.PlayerData.serializeBinaryToWriter
    );
  }
  f = message.getFramecount();
  if (f !== 0) {
    writer.writeInt32(
      2,
      f
    );
  }
};


/**
 * repeated PlayerData playerDatas = 1;
 * If you change this array by adding, removing or replacing elements, or if you
 * replace the array itself, then you must call the setter to update it.
 * @return {!Array.<!proto.tutorial.PlayerData>}
 */
proto.tutorial.GameData.prototype.getPlayerdatasList = function() {
  return /** @type{!Array.<!proto.tutorial.PlayerData>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.tutorial.PlayerData, 1));
};


/** @param {!Array.<!proto.tutorial.PlayerData>} value */
proto.tutorial.GameData.prototype.setPlayerdatasList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.tutorial.PlayerData=} opt_value
 * @param {number=} opt_index
 * @return {!proto.tutorial.PlayerData}
 */
proto.tutorial.GameData.prototype.addPlayerdatas = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.tutorial.PlayerData, opt_index);
};


proto.tutorial.GameData.prototype.clearPlayerdatasList = function() {
  this.setPlayerdatasList([]);
};


/**
 * optional int32 frameCount = 2;
 * @return {number}
 */
proto.tutorial.GameData.prototype.getFramecount = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/** @param {number} value */
proto.tutorial.GameData.prototype.setFramecount = function(value) {
  jspb.Message.setField(this, 2, value);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.tutorial.ClientInput = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.tutorial.ClientInput, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.tutorial.ClientInput.displayName = 'proto.tutorial.ClientInput';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.tutorial.ClientInput.prototype.toObject = function(opt_includeInstance) {
  return proto.tutorial.ClientInput.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.tutorial.ClientInput} msg The msg instance to transform.
 * @return {!Object}
 */
proto.tutorial.ClientInput.toObject = function(includeInstance, msg) {
  var f, obj = {
    movex: +jspb.Message.getFieldWithDefault(msg, 1, 0.0),
    movey: +jspb.Message.getFieldWithDefault(msg, 2, 0.0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.tutorial.ClientInput}
 */
proto.tutorial.ClientInput.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.tutorial.ClientInput;
  return proto.tutorial.ClientInput.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.tutorial.ClientInput} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.tutorial.ClientInput}
 */
proto.tutorial.ClientInput.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readFloat());
      msg.setMovex(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readFloat());
      msg.setMovey(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.tutorial.ClientInput.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.tutorial.ClientInput.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.tutorial.ClientInput} message
 * @param {!jspb.BinaryWriter} writer
 */
proto.tutorial.ClientInput.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getMovex();
  if (f !== 0.0) {
    writer.writeFloat(
      1,
      f
    );
  }
  f = message.getMovey();
  if (f !== 0.0) {
    writer.writeFloat(
      2,
      f
    );
  }
};


/**
 * optional float moveX = 1;
 * @return {number}
 */
proto.tutorial.ClientInput.prototype.getMovex = function() {
  return /** @type {number} */ (+jspb.Message.getFieldWithDefault(this, 1, 0.0));
};


/** @param {number} value */
proto.tutorial.ClientInput.prototype.setMovex = function(value) {
  jspb.Message.setField(this, 1, value);
};


/**
 * optional float moveY = 2;
 * @return {number}
 */
proto.tutorial.ClientInput.prototype.getMovey = function() {
  return /** @type {number} */ (+jspb.Message.getFieldWithDefault(this, 2, 0.0));
};


/** @param {number} value */
proto.tutorial.ClientInput.prototype.setMovey = function(value) {
  jspb.Message.setField(this, 2, value);
};


goog.object.extend(exports, proto.tutorial);
